# Generated by Django 3.2.4 on 2021-07-13 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210707_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.TextField(max_length=1000)),
                ('score', models.CharField(choices=[('A', 'Excelent'), ('B', 'Good'), ('C', 'Okay'), ('D', 'Bad'), ('F', 'Terrible')], default='A', max_length=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movie')),
            ],
        ),
    ]
